# Generated by Django 5.2.18 on 2026-10-09 09:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("learning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ModuleProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="course",
            name="modules_count",
        ),
        migrations.AddField(
            model_name="course",
            name="banner_icon",
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AddField(
            model_name="course",
            name="banner_key",
            field=models.CharField(
                blank=True,
                help_text="Which banner image the website shows: python, react, sql, communication, excel, time, leadership, presentation",
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="certificate_available",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="course",
            name="level",
            field=models.CharField(default="Beginner", max_length=20),
        ),
        migrations.AddField(
            model_name="course",
            name="meta",
            field=models.CharField(
                blank=True,
                help_text="Short line such as '8 Modules · 6h 30m'",
                max_length=60,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="rating",
            field=models.CharField(default="4.5", max_length=6),
        ),
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Used in page URLs, e.g. python-fundamentals. Auto-filled from the title.",
                max_length=80,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="trainer_name",
            field=models.CharField(
                blank=True,
                help_text="Name shown on the course, e.g. 'Mr. Aravind'. Leave blank to use the trainer account name.",
                max_length=80,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="task",
            name="estimated_time",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="task",
            name="priority",
            field=models.CharField(
                choices=[("High", "High"), ("Medium", "Medium"), ("Low", "Low")],
                default="Medium",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="submission",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="task",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("Assignment", "Assignment"),
                    ("Quiz", "Quiz"),
                    ("Project", "Project"),
                    ("Reading", "Reading"),
                ],
                default="Assignment",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("completed", "Completed")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.PositiveSmallIntegerField(default=1)),
                (
                    "slug",
                    models.CharField(
                        blank=True,
                        help_text="e.g. m1. Auto-filled from the order.",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "video_url",
                    models.URLField(
                        blank=True,
                        help_text="YouTube embed link, e.g. https://www.youtube.com/embed/xxxx",
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("notes_size", models.CharField(blank=True, max_length=20)),
                ("estimated_time", models.CharField(blank=True, max_length=30)),
                ("difficulty", models.CharField(default="Beginner", max_length=20)),
                (
                    "objectives",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='List of text lines, e.g. ["Learn A", "Learn B"]',
                    ),
                ),
                (
                    "due_after_days",
                    models.PositiveSmallIntegerField(
                        default=7,
                        help_text="Assignment deadline = enrollment date + this many days",
                    ),
                ),
                ("assignment_title", models.CharField(blank=True, max_length=150)),
                ("assignment_description", models.TextField(blank=True)),
                (
                    "assignment_tasks",
                    models.JSONField(
                        blank=True, default=list, help_text="List of text lines"
                    ),
                ),
                (
                    "assignment_estimated_time",
                    models.CharField(blank=True, max_length=30),
                ),
                (
                    "assignment_difficulty",
                    models.CharField(
                        default="Easy",
                        help_text="Easy, Medium or Advanced",
                        max_length=20,
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="learning.course",
                    ),
                ),
            ],
            options={
                "ordering": ["course", "order"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="learning.module",
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                condition=models.Q(("module__isnull", False)),
                fields=("employee", "module"),
                name="one_task_per_employee_module",
            ),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="enrollment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="module_progress",
                to="learning.enrollment",
            ),
        ),
        migrations.AddField(
            model_name="moduleprogress",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="completions",
                to="learning.module",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("course", "slug"), name="unique_module_slug_per_course"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moduleprogress",
            unique_together={("enrollment", "module")},
        ),
    ]
